### ISSUE TITLE
source code sharing

### ISSUE THREAD

**Issue by jamesYu365** [skzhangPKU/GTA#2]
Hello there, I have to say the model is great and I'm interest in adapting your work. I am wondering whether you can share your code?

**Comment by zouguojian** [comment]
Maybe there is problem, because I think the performance can not be better than GMAN. You can ask the author to share the GMAN weights and codes, or to retraining the GMAN model on theses paper datasets.

**Comment by jamesYu365** [comment]
OK, Thanks
